name: Wisecow CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t wisecow-app .
        
    - name: Test Docker image
      run: |
        docker run -d --name wisecow-test wisecow-app
        sleep 15
        docker logs wisecow-test
        docker stop wisecow-test
        docker rm wisecow-test
